### ISSUE TITLE
Manage Bookings

### ISSUE THREAD

**Issue by joshimans** [geiselperese/StrugglingDevelopers_RoomBookingSystem#1]
Create/Update/Add/Delete Booking records

**Comment by Chengze-Wu** [comment]
Get the error mesage: "Required int parameter 'userId' is not present"
Cannot pass id between two pages

**Comment by Chengze-Wu** [comment]
Finished Iteration 1.

**Comment by Chengze-Wu** [comment]
Unit test for booking entity.
