### ISSUE TITLE
Filter rooms

### ISSUE THREAD

**Issue by joshimans** [geiselperese/StrugglingDevelopers_RoomBookingSystem#2]
Filter rooms based on equipment available

**Comment by joshimans** [comment]
Fixed the bug for Parameter Index error with SQL - modified the query to filter the room records as expected.

**Comment by joshimans** [comment]
Added navigation bar for connectivity to booking page, tested it and pushed changes to git.

**Comment by eduardogeisel** [comment]
Tested filter rooms, everything is working smoothly! Thanks, Mansi!

**Comment by joshimans** [comment]
The feature has been completed as part of Iteration 1, closing this issue.
