### ISSUE TITLE
Login/Logout

### ISSUE THREAD

**Issue by eduardogeisel** [geiselperese/StrugglingDevelopers_RoomBookingSystem#3]
Users need to login before booking a room. This page will enable the users to login to their accounts. The user will be able to logout after using the system.  If the user does not have an account, he can create an account by clicking a sing up link that redirects the user to a sign up page.

**Comment by joshimans** [comment]
Tested login/logout feature.

**Comment by eduardogeisel** [comment]
Closing this issue since Iteration 1 is complete

**Comment by joshimans** [comment]
JUnit testing completed.
