### ISSUE TITLE
Add booking limitation (Admin Feature)

### ISSUE THREAD

**Issue by eduardogeisel** [geiselperese/StrugglingDevelopers_RoomBookingSystem#5]
The booking limitation is an Admin Feature that gives admins the ability to limit booking to certain rooms for only an amount of time, or even prevent a specific room from being booked at a certain time or day due to some scheduled maintenance, for instance.

**Comment by eduardogeisel** [comment]
I am facing merging conflicts when I try to pull the latest pushed version from GitHub into my remote repository.

**Comment by Chengze-Wu** [comment]
Help Eduardo to fix git merge conflicts.
