### ISSUE TITLE
Download Booking Confirmation

### ISSUE THREAD

**Issue by eduardogeisel** [geiselperese/StrugglingDevelopers_RoomBookingSystem#6]
Once the user has booked a room, he can opt to download the booking confirmation.

**Comment by joshimans** [comment]
Analysis for requirements for this feature in progress.

**Comment by joshimans** [comment]
Analysis completed - development of the feature in progress.

**Comment by joshimans** [comment]
Bug added: New booking not reflecting for Confirm booking feature in the database. Analyzing the bug.

**Comment by Chengze-Wu** [comment]
Bug fixed: add booking records to the database by using dao method

**Comment by joshimans** [comment]
Pulled form github and tested the code, the bug was fixed as part of Travis' code fix.

**Comment by joshimans** [comment]
Bug: Date being incorrectly written in database while booking room.

**Comment by joshimans** [comment]
Date bug fixed by Eduardo, Mansi and Travis.
