### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by eduardogeisel** [geiselperese/StrugglingDevelopers_RoomBookingSystem#7]
Calendar view - when user and admin views calendar, they can see what rooms are booked at that specific date.

**Comment by Chengze-Wu** [comment]
Cannot pass data from controller to <script> tag section

**Comment by Chengze-Wu** [comment]
Using jsp to access to model

**Comment by Chengze-Wu** [comment]
Cannot initialize fullCalendar with the customized events entity. Changed the previous events variable name from 'eventList' to 'events'. Solve the problem

**Comment by joshimans** [comment]
Bug: Date being incorrectly written in database while booking room.

**Comment by joshimans** [comment]
Date bug fixed by Eduardo, Mansi and Travis.
