### ISSUE TITLE
View Room Photos

### ISSUE THREAD

**Issue by joshimans** [geiselperese/StrugglingDevelopers_RoomBookingSystem#9]
Enable the user to view room pictures when filtering rooms

**Comment by eduardogeisel** [comment]
For some reason, the images are not showing up in the views... will try to fix it, if you guys can help figure this issue out, would be great @joshimans @Chengze-Wu

**Comment by eduardogeisel** [comment]
@Chengze-Wu helped me figure out what the bug was, I was missing a line of code. Now the images appear as they should in the program.

**Comment by Chengze-Wu** [comment]
View Room page cannot go back to other page since missing userId on context
